// Generated by Xata Codegen 0.30.1. Please do not edit.
import 'dotenv/config';
import { buildClient } from "@xata.io/client";
import type { BaseClientOptions } from "@xata.io/client";

export type DatabaseSchema = {};

const DatabaseClient = buildClient();
console.log("XATA_API_KEY:", process.env.XATA_API_KEY);
const defaultOptions = {
  databaseURL:
    "https://Pankaj-Birla-s-workspace-8e9e2b.eu-central-1.xata.sh/db/jsm_snapcast",
  apiKey: process.env.XATA_API_KEY,
  branch: 'main'
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options });
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
